walkerke/tidycensus

R/load_data.R

@walkerke this issue https://github.com/walkerke/tidycensus/issues/28#issuecomment-335118268 got me thinking. The `httr` package, which is already imported, has a neat function called `http_status()`, which returns the connection status of a call. In one of the user-examples in the issue, the user attempts to query data that aren't available, with this addition the user would receive the specific error message for the connection. The different types of error types for can be found [here](https://github.com/walkerke/tidycensus/issues/28#issuecomment-335118268) starting on line 66.
So, the user-error of:
```
income <- get_acs(geography = "place", variables = "B19013_001", survey = "acs1", endyear = 2010, key = Sys.getenv("CENSUS_API_KEY"))
```
...would return:
```
The one-year ACS provides …
```

Added connection status error handling.

---

R/helpers.R

Hello,
Thank you for the great package! I started to use it yesterday for the first time. I noticed that it changed my working directory after I saved an API key using the .Renviron helper. Taking a closer look, this doesn't seem like it's necessary and this small PR should change that behavior.
Thanks again!

don't change working directory when saving API key

---

R/acs.R

This is my first ever PR, so I'm not totally sure I'm doing it right. But here we go:
Found a bug when downloading new 2016 5-year estimates where some missing estimates return `-666666666` and missing MOE return `-222222222`. See below for example:
``` r
library(dplyr)
get_acs(
state = "GA",
county = "Fulton",
geography = "block group",
variables = "B01002_001",
survey = "acs5",
year = 2016,
geometry = FALSE,
) %>%
filter(GEOID == "131219800001") %>% # select bg with NA value
select(-NAME) # for nice printing
#> # A tibble: 1 x 4
#>          GEOID   variable   estimate        moe
#>          <chr>      <chr>      <dbl>      <dbl>
#> 1 131219800001 B01002_001 -666666666 -222222222
```
To deal with this, I simply changed the values in the `get_acs()` to replace …

Convert new missing values in 2016 5-year to NA

---

R/acs.R
R/load_data.R

In tidycensus 0.8.1 when trying to access ACS 1-year Subject tables, the call to the API fails:
``` r
get_acs(
geography = "state",
variables = "S2001_C01_002E",
survey = "acs1"
)
#> Getting data from the 2016 1-year ACS
#> The one-year ACS provides data for geographies with populations of 65,000 and greater.
#> Using the ACS Subject Tables
#> Error: One or more of your requested variables is likely not available at the requested geography.  Please refine your selection.
```
Calling the 5-year Subject tables works as expected:
``` r
get_acs(
geography = "state",
variables = "S2001_C01_002E",
survey = "acs5"
)
#> Getting data from the 2012-2016 5-year ACS
#> Using the ACS Subject Tables
#> # A tibble: 52 x 5
#>    GEOID NAME                 variable      estimate   moe
#>    <chr> <chr> …
```

fix api call for acs1 subject tables

---

R/load_data.R
R/search_variables.R

This fixes #128 by replacing the deprecated `tbl_df()` with `as_tibble(x, .name_repair = "minimal")` . Error when using dev version of `tibble` was caused by [new name checking/repair defaults in `as_tibble`]( https://github.com/tidyverse/tibble/blob/master/NEWS.md#breaking-changes).
I've tested it a bit with the current CRAN version of tibble (1.4.2) and it seems to be working with both the CRAN version and the dev version (1.4.99.9005).

fix check name errors introduced with tibble 1.5

---

R/utils.R

In response to #161, this changes the error handling for `validate_state()` and `validate_county()` so an error message is returned (instead of `NULL`) if a user enters a county that is not valid or matches multiple valid counties in the lookup. @walkerke, I'm not sure if no longer returning NULL will break something else down the line, but in a little ad-hoc testing I did, I didn't run into any problems.
Currently you get this:
```
> get_acs(
+   geography = "county",
+   variables = "B19013_001",
+   state = "TX",
+   county = "Harris"
+ )
Getting data from the 2013-2017 5-year ACS
Using FIPS code '48' for state 'TX'
Error: Result 1 must be a single string, not NULL of length 0
Call `rlang::last_error()` to see a backtrace
> 
```
With this PR you get:
```
> get_acs(
+   geography = …
```

Return informative error message for multiple county matches

---

R/acs.R

When a large number of variables (>24) are passed into `get_acs`, results sometimes (perhaps rarely) contain errors (perhaps many). This is because `get_acs` divides the variables into two or more requests, and then binds the returned results together into a dataframe, but GEOIDs may be ordered differently for each set of returned results.  For example:
```
variables <- c("B01001_003", "B01001_004", "B01001_005", "B01001_006", "B01001_007", 
"B01001_008", "B01001_009", "B01001_010", "B01001_011", "B01001_012", 
"B01001_013", "B01001_014", "B01001_015", "B01001_016", "B01001_017", 
"B01001_018", "B01001_019", "B01001_020", "B01001_021", "B01001_022", 
"B01001_023", "B01001_024", "B01001_025", "B01001_026", "B25002_002",
"B03003_003")
test1 <- get_acs(geography = …
```

Fixed bug when GEOIDs are ordered differently in result chunks.

---

R/search_variables.R

This fixes https://github.com/walkerke/tidycensus/issues/122#issuecomment-499181316, by using the old API endpoint when running `load_variables()` for `year = 2009`.

use old end point for 2009 api in load_variables

---

R/acs.R
R/census.R
R/estimates.R
R/load_data.R
R/search_variables.R
man/get_acs.Rd
man/get_decennial.Rd
man/get_estimates.Rd

In reference to #194, this adds an option to the three `get_*()` functions to print the API call that is sent to the Census API. This enables a user to copy and paste the API call into a browser and help to determine if the issue is with tidycensus or the Census API if they are receiving an error. 
When the request requires multiple calls to the API because of a large number of variables, all API calls are printed. But, because messages are suppressed internally when making iterating over `get_*()` calls (required for block groups or multi-state tract level requests), the API calls are not printed. 
Below are examples of the API call printing.
Also another commit to change the default year for `get_estimates()` to 2018 in re #200.
``` r
get_acs(
geography = "state", …
```

Add show_call option to get_*() to print API calls

---

R/acs.R

The census API now allows users to access 1 year acs data for 2010 and 2011. In response to issue #199, I removed the legacy stop that halts get_acs if user requests data from before 2012.
I could have adjusted the if statement to stop the function if a pre-2010 date was entered, but (hopefully!) the good folks at the census will eventually make 2005-2009 1 year data available via the API. Considering many other mis-specifications can cause get_acs's GET command to fail in a less pretty manner (for example specifying a year of data that does not yet exist) it didn't seem necessary to me to keep the stop at all. 
Heads up this is my first time contributing to code before--feedback welcome, I'm looking to learn. Thanks for this awesome tool!

remove ACS1 pre-2012 limitation

---

R/acs.R

Oops! As reported in #216, I forgot about subject tables that begin with `C`, so when I added the logic to enable subject, profile, and summary tables in a single `get_acs()` call, it dropped any variables starting with `C`.
This fix should take care of it!
``` r
minilist <- c("C17002_002","C17002_003","C21007_027","C21007_030",
"B01001_001","B01001_020","B01001_021","B08301_003","B08301_021")
test <- get_acs(
"block group",
variables = minilist,
state = "OH",
county = "Cuyahoga",
year = 2017
)
#> Getting data from the 2013-2017 5-year ACS
all(minilist %in% unique(test$variable))
#> [1] TRUE
get_acs(
geography = "state",
variables = c("C17002_002", "B01001_001", "S1701_C03_002", "DP02_0045")
)
#> Getting data from the 2014-2018 5-year ACS
#> Fetching data by table type …
```

Fix bug where 'C' variables are dropped if included with 'B' variables in a single get_acs call

---

R/moe.R

When `moe_prop` avoids using a result based on the square root of a negative
number, it can still calculate it and raise a warning.
This is because `ifelse` usually evaluates both possible vectors, and then
picks which elements to use.

Avoid warnings in moe_prop from square roots of negatives

---

R/acs.R
R/census.R

Allow users to specify geography="cbg" for "block group"

Make alias for "block group" as "cbg"

---

R/fips_codes.R
man/fips_codes.Rd

In response to #221, add a note in the `fips_codes` docs indicated that counties included in the dataset are not from a specific census vintage, but include all counties from 2010 to present.

update fips_code docs

---

R/acs.R
R/load_data.R
R/search_variables.R

This PR adds support in `get_acs()` for the [ACS 1-year Supplemental Estimates API](https://www.census.gov/data/developers/data-sets/ACS-supplemental-data.html), which gives 1-year estimates for smaller geographies (down to population 20,000 and up).  Variables in the supplemental estimates start with K.

Supplemental estimates

---

DESCRIPTION
R/census.R
man/county_laea.Rd
man/fips_codes.Rd
man/state_laea.Rd

Looks like this small change will fix the error reported in #229. Here it is working with dplyr 0.8.99.9002 and sf 0.9.0 installed.
This dplyr change doesn't seem to impact `get_acs()` with large numbers of variables as the logic for combining the returned tibbles is different in `get_acs()`: https://github.com/mfherman/tidycensus/blob/d41bbc5f3c30d85506e654f7303e51080144d4c8/R/acs.R#L659
``` r
vars <- load_variables(2010, "sf1", cache = TRUE)
get_decennial(
geography = "state",
state = "VT",
variables = vars$name[1:49]
)
#> Getting data from the 2010 decennial Census
#> # A tibble: 49 x 4
#>    GEOID NAME    variable  value
#>    <chr> <chr>   <chr>     <dbl>
#>  1 50    Vermont H001001  322539
#>  2 50    Vermont H002001  322539
#>  3 50    Vermont H002002  106561
#> …
```

fix get_decennial() to work with dplyr 1.0 when requesting >48 vars

---

R/moe.R

Adjusting logic for when x is NA. Cannot use index with NA
``` r
x <- c(1, 2, 3, 4, 0, -1, NA)
y <- 1:length(x)*100
(pos_x <- x >= 0 )
#> [1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE    NA
y[pos_x] <- x[pos_x]
#> Error in y[pos_x] <- x[pos_x]: NAs are not allowed in subscripted assignments
y
#> [1] 100 200 300 400 500 600 700
x <- c(1, 2, 3, 4, 0, -1, NA)
y <- 1:length(x)*100
(pos_x <- x >= 0 & !is.na(x))
#> [1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE
y[pos_x] <- x[pos_x]
y
#> [1]   1   2   3   4   0 600 700
```
<sup>Created on 2020-04-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Fixing bad behavior in moe_prop when values involve NA

---

R/load_data.R
R/pums.R
man/df_to_svyrep.Rd

Not sure if this is what you had in mind for the `rep_weights` argument. I also borrowed some logic from the other load_* functions to split the variable vector when too large. The PUMS API endpoint seems to take up to 50 variables in one call.
Also created a little wrapper around `survey::svrepdesign()` to create a survey object. Not sure if this belongs in tidycensus, or as you said just in a vignette about how to analyze PUMS data.

implement rep_weights argument for get_pums()

---

R/acs.R

In re this warning message when `output = "wide"` in `get_acs()`. I don't believe the `funs()` wrapper has been needed for a while, so this shouldn't impact anything. Candidly, I didn't spend much time testing, @walkerke you might want to kick the tires just a bit!
```r
Warning message:
`funs()` is deprecated as of dplyr 0.8.0.
Please use a list of either functions or lambdas: 
list(mean = mean, median = median)
tibble::lst(mean, median)
list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

remove deprecated `funs()` from get_acs()

---

.travis.yml
DESCRIPTION
R/acs.R
R/significance.R
man/significance.Rd

get_acs now throws a warning for the mutate_if call using the depreciated `funs`. Updated to 0.8.0 `list` syntax instead. Note that list is supercede in 1.0, but not depreciated, so I've defaulted to 0.8.0 to maximize compatibility.

Update dplyr to 0.8.0

---

R/census.R
R/load_data.R
vignettes/basic-usage.Rmd

2000 decennial data is now available in new endpoint and includes many more geographies than the old endpoint. 
New: https://api.census.gov/data/2000/dec/sf1/geography.html
Old: https://api.census.gov/data/2000/sf1/geography.html
Some discussion [here](https://uscensusbureau.slack.com/archives/CC76279UH/p1598539227002400) and [here](https://uscensusbureau.slack.com/archives/C6DGLC05B/p1598534150024500). Right now, this is only available for Summary File 1. Unclear if SF3 will be added in the future.
I also updated the table in the Basic Usage vignette to reflect newly available geographies in `get_decennial()`.

2000 decennial endpoint update

---

R/acs.R
R/load_data.R
man/get_acs.Rd

Based on #287, added a new parameter to `get_acs()` to specify one or more ZCTAs. You can pass a numeric or character vector of ZCTAs. When `geometry = TRUE`, entire ZCTA shapefiles are pulled from Census, but only selected ZCTAs are included in results.
I added some error messages if a user specifies ZCTAs and `geography != "ZCTA"`, or if using the `state`/`county` along with the `zcta` argument.
I started to work on adding this option to `get_decennial()` but I realized that there are more geography options with the decennial API so that are you are able to select ZCTAs within states already. Because of this, the GEOIDs used for pulling ZCTA data are state + zip code (e.g. `3610536` rather than just `10536`). This makes it a bit trickier to implement the ability to select ZCTAs in the …

Add option to request a subset of zctas in get_acs()

---

R/acs.R

@walkerke I made a mess of the commit history in the prior PR (#321), so I've just opened a new one here. I probably should get better at git ;)
Small fix that addresses #319 -- previous implementation stripped the names from the variable vector input and thus wouldn't rename variables. This fix keeps the names when splitting the requested variables into a list by table type.

Fix bug that removed custom names in get_acs when variables from more than one table type requested

---

R/acs.R
R/census.R
R/search_variables.R
man/get_acs.Rd
man/load_variables.Rd

A few small changes here:
- Re: #329, this allows `get_acs()` to access 1-year data beginning in 2005 and 3-year beginning in 2007. @walkerke am I remembering that data from these years used to be in a different format in the API? I did a bit of informal testing and everything seems to be working on my end.
- Re: #293, 2000 SF3 data is [back up on the API](https://uscensusbureau.slack.com/archives/C6DGLC05B/p1607100621206000), so I simply removed the stop logic in `get_decennial()`
- Because I added support for earlier datasets in `get_acs()`, I took a look at `load_variables()` and simplified the logic because it appears that all endpoints now have variables available as JSON.
@walkerke I'd appreciate a bit of testing on these changes when you have a chance...I did some informal checks, …

Various changes: support for earlier years ACS, enable 200 SF3, simplify load_variables

---

R/estimates.R
R/load_data.R
man/get_estimates.Rd

I was recently attempting to use `get_estimates()` for the first time, and was having a hard time finding the cause of some error messages I was receiving. I'm submitting this pull request to make the error messages a little bit more informative in these particular use cases.
I was initially hopeful that I could use the `variables` parameter to specify variables from multiple products, e.g. `variables=c("POP","HUEST")`. Nothing in the documentation suggested this was not allowed (although I realize it would require the results of multiple API calls to be combined). The parameter description says "A character string of requested variables to get specific variables from the population, components, **and** housing APIs" (emphasis mine). 
I have updated the parameter description to read "A …

Improved error handling and documentation for get_estimates()

---

DESCRIPTION
R/load_data.R

Re: #365 Fix bug where ST was not included when state = "all" in get_pums causing an error in pivot_longer step

Fix get_pums bug when state = "all"

---

R/acs.R
R/census.R
R/estimates.R
R/flows.R
R/pums.R

Thanks putting in the work for this wonderful package. This PR adds parentheses to warning mentions of the function `census_api_key()`. Using parentheses to distinguish functions from other R objects appears to be a tidy convention. See this example involving `create_package()` https://r-pkgs.org/whole-game.html#create_package

Add parentheses to mentions of census_api_key()

---

R/acs.R

typo in example (`geom_errorbarh`). Changed to `geom_errorbar`, which also allows for passing additional values, parameters and constraints (e.g., `width` and `size` as I've added by way of example).

Fixed typo and updated example

---

DESCRIPTION
R/load_data.R
R/pums.R
man/get_pums.Rd

See issue #405.  Makes separate calls to the API - one for non-vacant units (which can have person-level characteristics) and one for vacant units (which will disappear from an API call when person-level characteristics are requested) and combines the result.  
cc @mfherman @szimmer if you are interested in putting eyes on this.

Correctly return vacant housing units in `get_pums()`

---

R/search_variables.R
man/load_variables.Rd

This PR makes the error messages thrown by `load_variables` a little more user friendly. 
An error will now throw if `year` is not a single, 4 digit number (either character or numeric). Previously, the function would continue and throw confusing error messages
Old
```
> load_variables(year = c(2005, 2006), 'acs1')
Error in parse_url(url) : length(url) == 1 is not TRUE
In addition: Warning message:
In if (year == 1990) { :
the condition has length > 1 and only the first element will be used
```
New
```
> load_variables(year = c(2005, 2006), 'acs1')
Error in load_variables(year = c(2005, 2006), "acs1") : 
Argument "year" must be a single year in format YYYY.
```
Old
```
> load_variables(year = "06", 'acs1')
Error: 1-year ACS support in tidycensus begins with the 2005 1-year ACS. Consider …
```

more informative error messages in load_variables

---

R/estimates.R
man/get_estimates.Rd

Addresses https://github.com/walkerke/tidycensus/issues/445
- Adds acceptable values for `geography` to function definition and validates with `arg_match`
- Adds note about using 2019 vintage data even for previous years

list geography for get_estimates

---

R/utils.R

Check to see if `from`, `to`, and `weights` have the same CRS if CRS is not supplied as a function argument to `interpolate_pw()`. This saves time if `weights` is large and a long time is spent generating centroids before `sf::st_join()` will inevitably fail when trying to create `denomiators` due to the mismatched CRS.

Throw errorin interpolate_pw() if inputs have different CRS and CRS not supplied

---

R/utils.R

Updated CRS check in `interpolate_pw()` function to handle identical CRS among `from`, `to`, and `weights` objects. The modification does the following:
- First, checks IF all objects have a valid CRS.
- If `TRUE`,
- Then, checks IF the CRSs of the objects are (not) identical to each other,
- If `TRUE`, 
- IF `CRS` argument is supplied, transforms all object to the supplied `CRS`
- `ELSE` provides error

Resolve issue #605
